import { MovieVideoStatus } from '../types';

export const MOVIE_STATUS_LIST: MovieVideoStatus[] = [
  // 1. BOLLYWOOD (HINDI)
  {
    id: 'bolly-d-1',
    title: 'Babumoshai, Zindagi Badi Honi Chahiye',
    movie: 'Anand (1971)',
    language: 'hi',
    type: 'dialogue',
    genre: 'motivational',
    actorOrSinger: 'Rajesh Khanna & Amitabh Bachchan',
    dialogueOrLyrics: 'बाबूमोशाय, ज़िन्दगी बड़ी होनी चाहिए, लंबी नहीं! जब तक जीयो, शान से जीयो और हर पल का शुक्रिया अदा करो।',
    translatedText: 'Babumoshai, life should be grand, not merely long! Live each moment with joy and gratitude.',
    soundSnippetType: 'acoustic-guitar',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#3b1808', '#632b0c'],
    viewsCount: '1.2M',
    likesCount: 94000,
  },
  {
    id: 'bolly-d-2',
    title: 'Pushpa Style Hindi Swag - झुकेगा नहीं',
    movie: 'Pushpa: The Rise (Hindi)',
    language: 'hi',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Allu Arjun (Voice: Shreyas Talpade)',
    dialogueOrLyrics: 'पुष्पा, पुष्पा राज... मैं झुकेगा नहीं साला! नाम सुन के फ्लावर समझे क्या? फायर है मैं!',
    translatedText: 'Pushpa Raj... I will never bow down! Did you think I am a flower? I am fire!',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 18,
    isPremium: false, // FREE
    gradientColors: ['#2e0c05', '#57180c'],
    viewsCount: '2.8M',
    likesCount: 210000,
  },
  {
    id: 'bolly-s-1',
    title: 'Tum Hi Ho - Soulful Romance',
    movie: 'Aashiqui 2',
    language: 'hi',
    type: 'song',
    genre: 'romantic',
    actorOrSinger: 'Arijit Singh',
    dialogueOrLyrics: 'क्योंकि तुम ही हो, अब तुम ही हो, ज़िंदगी अब तुम ही हो... चैन भी, मेरा दर्द भी, मेरी आशिक़ी अब तुम ही हो।',
    translatedText: 'Because it is you, now only you... my life is only you. My peace, my ache, my devotion is you.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 22,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#380b18', '#6b132e'],
    viewsCount: '3.4M',
    likesCount: 340000,
  },
  {
    id: 'bolly-d-3',
    title: 'Don Ko Pakadna Mushkil Hi Nahi...',
    movie: 'Don',
    language: 'hi',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Amitabh Bachchan / Shah Rukh Khan',
    dialogueOrLyrics: 'डॉन को पकड़ना मुश्किल ही नहीं... नामुमकिन है! जो चीज़ मुझे पसंद आ जाए, वो मेरे हाथ से नहीं छूटती।',
    translatedText: 'Catching Don is not just difficult... it is impossible! What I desire never slips away.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 16,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#12131c', '#242738'],
    viewsCount: '1.9M',
    likesCount: 165000,
  },

  // 2. TOLLYWOOD (TELUGU)
  {
    id: 'tol-d-1',
    title: 'Thaggedhe Le - తగ్గేదే లే!',
    movie: 'Pushpa: The Rise',
    language: 'te',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Allu Arjun',
    dialogueOrLyrics: 'పుష్ప.. పుష్పరాజ్! తగ్గేదే లే! పేరు వినగానే పూలనుకున్నావా? అగ్గిరవ్వని!',
    translatedText: 'Pushpa.. Pushpa Raj! No backing down! Did you think I was soft like a flower? I am wildfire!',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#2b0d07', '#57180c'],
    viewsCount: '3.1M',
    likesCount: 290000,
  },
  {
    id: 'tol-d-2',
    title: 'Naa Maate Shaasanam - నా మాటే శాసనం',
    movie: 'Baahubali: The Beginning',
    language: 'te',
    type: 'dialogue',
    genre: 'motivational',
    actorOrSinger: 'Prabhas / Sivagami Devi',
    dialogueOrLyrics: 'ఇది నా మాట... నా మాటే శాసనం! ధర్మం కోసం నిలబడే వాడికి భయం ఉండదు.',
    translatedText: 'This is my word... and my word is the law! He who stands for righteousness knows no fear.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#281203', '#4a250a'],
    viewsCount: '2.4M',
    likesCount: 180000,
  },

  // 3. KOLLYWOOD (TAMIL)
  {
    id: 'kol-d-1',
    title: 'Naan Oru Thadava Sonna - நான் ஒரு தடவ சொன்னா...',
    movie: 'Baashha',
    language: 'ta',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Superstar Rajinikanth',
    dialogueOrLyrics: 'நான் ஒரு தடவ சொன்னா... நூறு தடவ சொன்ன மாதிரி! கெத்துனா என்னன்னு நாங்க சொல்லித் தர தேவையில்ல.',
    translatedText: 'If I say it once, it is as good as saying it a hundred times! We need not teach what real swag is.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#1f0a0d', '#42161d'],
    viewsCount: '2.7M',
    likesCount: 230000,
  },
  {
    id: 'kol-d-2',
    title: 'Aarambikkalangala - ஆரம்பிக்கலாங்களா',
    movie: 'Vikram',
    language: 'ta',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Kamal Haasan (Anirudh BGM)',
    dialogueOrLyrics: 'பார்த்து பல நாள் ஆச்சு... ஆரம்பிக்கலாங்களா? வேட்டையாட ஆரம்பிச்சா வேடன் தான் நிப்பான்!',
    translatedText: 'It has been quite a while... Shall we begin? When the hunt starts, only the master stands.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 16,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#141724', '#262d47'],
    viewsCount: '3.6M',
    likesCount: 310000,
  },

  // 4. POLLYWOOD (PUNJABI)
  {
    id: 'pun-d-1',
    title: 'Advocate Dhillon Ne Kala Coat Aiven Ni Paaya!',
    movie: 'Carry On Jatta',
    language: 'pa',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Jaswinder Bhalla & Gippy Grewal',
    dialogueOrLyrics: 'ਐਡਵੋਕੇਟ ਢਿੱਲੋਂ ਨੇ ਕਾਲਾ ਕੋਟ ਐਵੇਂ ਨੀ ਪਾਇਆ! ਜਿੱਥੇ ਖੜ੍ਹ ਜਾਈਏ, ਉੱਥੇ ਫ਼ੈਸਲੇ ਪੱਕੇ ਹੁੰਦੇ ਨੇ।',
    translatedText: 'Advocate Dhillon did not wear this black coat for fun! Where we stand, judgments are sealed.',
    soundSnippetType: 'bhangra-dhol',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#2e1505', '#52270d'],
    viewsCount: '1.8M',
    likesCount: 145000,
  },
  {
    id: 'pun-s-1',
    title: 'Sidhu Moosewala 295 - Attitude Anthem',
    movie: 'Moosetape',
    language: 'pa',
    type: 'song',
    genre: 'motivational',
    actorOrSinger: 'Sidhu Moosewala',
    dialogueOrLyrics: 'ਦੱਸ ਕੀਹਦੇ ਸਿਰ ਇਲਜ਼ਾਮ ਧਰੇਂਗਾ... ਸੱਚ ਬੋਲੇਂਗਾ ਤਾਂ 295 ਲੱਗੂ, ਕਰੇਂਗਾ ਤਰੱਕੀ ਤਾਂ ਹੇਟ ਮਿਲੂਗੀ!',
    translatedText: 'Whom will you blame? If you speak the truth they penalize you; if you rise, you face jealousy.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 20,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#121014', '#2b2430'],
    viewsCount: '4.2M',
    likesCount: 420000,
  },

  // 5. BENGALI CINEMA (TOLLYWOOD)
  {
    id: 'ben-d-1',
    title: 'আমার কাছে ছবির কোনো শর্টকাট নেই',
    movie: 'Nayak (Hero) - Satyajit Ray',
    language: 'bn',
    type: 'dialogue',
    genre: 'motivational',
    actorOrSinger: 'Uttam Kumar (Mahanayak)',
    dialogueOrLyrics: 'জনপ্রিয়তা ধরে রাখার একটাই নিয়ম—কখনও নিজের আত্মমর্যাদাকে সস্তা হতে না দেওয়া।',
    translatedText: 'There is only one rule to maintain true honor—never allow your self-respect to be cheapened.',
    soundSnippetType: 'acoustic-guitar',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#1a1f2b', '#2f384d'],
    viewsCount: '890K',
    likesCount: 78000,
  },
  {
    id: 'ben-s-1',
    title: 'তুমি আসবে বলে তাই - Romantic Melancholy',
    movie: 'Bhooter Bhabishyat / Kabir Suman',
    language: 'bn',
    type: 'song',
    genre: 'romantic',
    actorOrSinger: 'Kabir Suman / Nachiketa',
    dialogueOrLyrics: 'তুমি আসবে বলেই আকাশ মেঘলা, বৃষ্টি এখনও হয়নি... তুমি আসবে বলেই আমি একলা পথের ধারে দাঁড়িয়ে আছি।',
    translatedText: 'Because you are to arrive, the sky gathers clouds... Because you are to arrive, I wait with quiet hope.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 22,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#241221', '#472242'],
    viewsCount: '1.1M',
    likesCount: 96000,
  },

  // 6. BHOJPURI CINEMA
  {
    id: 'bho-d-1',
    title: 'पवन सिंह धाकड़ भौकाल डायलॉग',
    movie: 'Sher Singh (Bhojpuri)',
    language: 'bho',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Pawan Singh (Power Star)',
    dialogueOrLyrics: 'शेर जब शांत रहेला त समझे के चाहीं कि शिकार के तैयारी बा! हमार नामे काफ़ी बा इलाका में खलबली मचावे खातिर।',
    translatedText: 'When the lion is silent, know that the hunt is ready! My name alone is enough to shake the ground.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#331505', '#59250a'],
    viewsCount: '1.5M',
    likesCount: 130000,
  },
  {
    id: 'bho-s-1',
    title: 'लॉलीपॉप लागेलु - Global Bhojpuri Hit',
    movie: 'Pawan Singh Hits',
    language: 'bho',
    type: 'song',
    genre: 'festive',
    actorOrSinger: 'Pawan Singh',
    dialogueOrLyrics: 'कमरिया करे लपालप, कि लॉलीपॉप लागेलु! पूरा यूपी-बिहार तोहपे फिदा बा हो!',
    translatedText: 'Your grace is captivating; the entire world dances to your rhythm!',
    soundSnippetType: 'festive-shehnai',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#300918', '#5e1331'],
    viewsCount: '5.1M',
    likesCount: 480000,
  },

  // 7. KANNADA CINEMA (SANDALWOOD)
  {
    id: 'kan-d-1',
    title: 'Violence, Violence, Violence! I Avoid... But Violence Likes Me!',
    movie: 'KGF: Chapter 2',
    language: 'kn',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Rocking Star Yash',
    dialogueOrLyrics: 'Violence... Violence... Violence! I don’t like it, I avoid! But... Violence likes me, I can’t avoid!',
    translatedText: 'Violence... Violence... Violence! I avoid it, but violence loves me!',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#1c1917', '#36302c'],
    viewsCount: '4.8M',
    likesCount: 520000,
  },

  // 8. MARATHI CINEMA
  {
    id: 'mar-d-1',
    title: 'कुणी घर देतं का घर - नटसम्राट',
    movie: 'Natsamrat',
    language: 'mr',
    type: 'dialogue',
    genre: 'sad',
    actorOrSinger: 'Nana Patekar',
    dialogueOrLyrics: 'कुणी घर देतं का घर? एका वादळात सापडलेल्या नटाला कोणी घर देतं का? आपलं म्हणणारं कुणी उरलं नाही...',
    translatedText: 'Will someone offer a home? To an actor caught in the storm of life, is there any shelter left?',
    soundSnippetType: 'sad-sitar',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#1c1626', '#352a4a'],
    viewsCount: '1.3M',
    likesCount: 112000,
  },

  // 9. GUJARATI CINEMA
  {
    id: 'guj-d-1',
    title: 'લોચો પડ્યો ભાઈ - છેલ્લો દિવસ',
    movie: 'Chhello Divas',
    language: 'gu',
    type: 'dialogue',
    genre: 'festive',
    actorOrSinger: 'Malhar Thakar & Friends',
    dialogueOrLyrics: 'દોસ્તીમાં ક્યારેય હિસાબ-કિતાબ નથી હોતો, જે દિલથી સાથે રહે એ જ સાચો ભાઈબંધ કહેવાય!',
    translatedText: 'Friendship never keeps accounts; the one who stands with you with all their heart is a true brother!',
    soundSnippetType: 'acoustic-guitar',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#2b1807', '#4f2c0d'],
    viewsCount: '920K',
    likesCount: 84000,
  },

  // 10. HARYANVI CINEMA & RAGNI
  {
    id: 'har-d-1',
    title: 'देसी हरियाणवी ठाठ व भाईचारा',
    movie: 'Desi Haryanvi Swag',
    language: 'hr',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Uttar Kumar / Ajay Hooda',
    dialogueOrLyrics: 'हौंसले बुलन्द अर यार जिगरी हों तो दुनिया की कोई ताकत रोक नी सकदी! ठाठ देसी ए बढ़िया सै लाडलो।',
    translatedText: 'With high courage and loyal brothers, no force in the world can stop you! Pure desi pride.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 16,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#2b1406', '#4d240a'],
    viewsCount: '1.7M',
    likesCount: 155000,
  },
  {
    id: 'har-s-1',
    title: 'गजबन पाणी ने चाली - Folk Celebration',
    movie: 'Haryanvi Folk Hits',
    language: 'hr',
    type: 'song',
    genre: 'festive',
    actorOrSinger: 'Sapna Choudhary / Vishvajeet Choudhary',
    dialogueOrLyrics: 'गजबन पाणी ने चाली, सारा गाम देखे खड़ा! रूप तेरा ऐसा चमकै जैसे चंदा हो कड़ा।',
    translatedText: 'Her grace captivates the whole village; glowing bright as the moon!',
    soundSnippetType: 'festive-shehnai',
    durationSeconds: 18,
    isPremium: false, // FREE
    gradientColors: ['#381105', '#69200b'],
    viewsCount: '3.9M',
    likesCount: 310000,
  },

  // 11. ODIA CINEMA (OLLWOOD)
  {
    id: 'odi-d-1',
    title: 'ମୁଁ ଓଡ଼ିଆ ଟୋକା, ମୋତେ କେହି ବାନ୍ଧି ପାରିବେନି!',
    movie: 'Mu Premi Mu Pagala / Ollywood Swag',
    language: 'or',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Anubhav Mohanty / Babushaan',
    dialogueOrLyrics: 'ମୁଁ ଓଡ଼ିଆ ଟୋକା, ଯେବେ ଯାଏଁ ସାହାସ ଅଛି ସେବେ ଯାଏଁ କାହା ଆଗରେ ମୁଣ୍ଡ ନୁଆଁଇବି ନାହିଁ!',
    translatedText: 'I am an Odia boy! As long as courage beats within me, I shall bow before no adversity!',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#2e1507', '#57250a'],
    viewsCount: '860K',
    likesCount: 74000,
  },
  {
    id: 'odi-s-1',
    title: 'ରଙ୍ଗବତୀ ରଙ୍ଗବତୀ - Iconic Sambalpuri Folk',
    movie: 'Rangabati - Jitendra Haripal',
    language: 'or',
    type: 'song',
    genre: 'festive',
    actorOrSinger: 'Jitendra Haripal & Krishna Patel',
    dialogueOrLyrics: 'ରଙ୍ଗବତୀ ରଙ୍ଗବତୀ କନକଲତା ହସି ପଦେ କଥା କହ... ମନ ତୋର କାହିଁକି ଆଜି ଏତେ ଉଲ୍ଲାସ!',
    translatedText: 'Rangabati, radiant one, speak with a tender smile... Why does the heart brim with such festive joy!',
    soundSnippetType: 'festive-shehnai',
    durationSeconds: 20,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#29081a', '#541237'],
    viewsCount: '2.1M',
    likesCount: 195000,
  },

  // 12. INDIAN ENGLISH (PAN-INDIA / OTT)
  {
    id: 'eng-d-1',
    title: 'How is the Josh? High Sir!',
    movie: 'URI: The Surgical Strike',
    language: 'en',
    type: 'dialogue',
    genre: 'motivational',
    actorOrSinger: 'Vicky Kaushal',
    dialogueOrLyrics: 'How is the josh? High Sir! How is the josh? High Sir! It is time for revenge, and time for valor!',
    translatedText: 'Courage running at maximum peak in every Indian heart!',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 15,
    isPremium: false, // FREE
    gradientColors: ['#121926', '#223049'],
    viewsCount: '5.2M',
    likesCount: 620000,
  },
  {
    id: 'eng-s-1',
    title: 'Maa Tujhe Salaam - Vande Mataram Anthem',
    movie: 'A.R. Rahman Hits',
    language: 'en',
    type: 'song',
    genre: 'motivational',
    actorOrSinger: 'A. R. Rahman',
    dialogueOrLyrics: 'Here is a prayer, here is a pledge... Vande Mataram! In your soil lies my heartbeat and my pride.',
    translatedText: 'Salutations to the motherland; eternal devotion and love.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 22,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#181a30', '#323766'],
    viewsCount: '4.6M',
    likesCount: 510000,
  },

  // 13. MORE BOLLYWOOD FESTIVE & ROMANTIC
  {
    id: 'bolly-s-2',
    title: 'Apna Bana Le Piya - Romantic Melodic Bliss',
    movie: 'Bhediya',
    language: 'hi',
    type: 'song',
    genre: 'romantic',
    actorOrSinger: 'Arijit Singh & Sachin-Jigar',
    dialogueOrLyrics: 'अपना बना ले पिया, अपना बना ले पिया... दिल के नगर में किसी और को आने ना दिया।',
    translatedText: 'Make me your own, my beloved... In the sanctuary of my heart, none else could ever enter.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#2b0d1e', '#59163b'],
    viewsCount: '3.8M',
    likesCount: 390000,
  },
  {
    id: 'bolly-d-4',
    title: 'Mogambo Khush Hua!',
    movie: 'Mr. India',
    language: 'hi',
    type: 'dialogue',
    genre: 'attitude',
    actorOrSinger: 'Amrish Puri',
    dialogueOrLyrics: 'मोगैम्बो खुश हुआ! जो अपनी तक़दीर खुद लिखते हैं, वही इतिहास बनाते हैं।',
    translatedText: 'Mogambo is pleased! Those who carve their own fate write history.',
    soundSnippetType: 'mass-bgm',
    durationSeconds: 15,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#1a1005', '#3b250c'],
    viewsCount: '2.1M',
    likesCount: 175000,
  },

  // ==========================================
  // 14. DEVOTIONAL SHORT VIDEO STATUSES (MULTILINGUAL BHAKTI)
  // ==========================================

  // (A) HINDI DEVOTIONAL
  {
    id: 'dev-hi-1',
    title: 'हनुमान चालीसा अमृत वाणी · संकटमोचन',
    movie: 'श्री हनुमान चालीसा (Shree Hanuman Chalisa)',
    language: 'hi',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Gulshan Kumar / Hariharan',
    dialogueOrLyrics: 'नासे रोग हरे सब पीरा, जपत निरंतर हनुमत बीरा! संकट तें हनुमान छुड़ावै, मन क्रम बचन ध्यान जो लावै॥',
    translatedText: 'All diseases and sorrows vanish by constantly remembering Lord Hanuman; he frees us from every crisis.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#3b1803', '#662a04'],
    viewsCount: '9.4M',
    likesCount: 980000,
  },
  {
    id: 'dev-hi-2',
    title: 'महाकाल की दिव्य शक्ति · अकाल मृत्यु वो मरे',
    movie: 'उज्जैन महाकाल भस्म आरती',
    language: 'hi',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'महाकाल भक्त (Mahakal Bhakt)',
    dialogueOrLyrics: 'अकाल मृत्यु वो मरे जो काम करे चंडाल का, काल उसका क्या करे जो भक्त हो महाकाल का! ॐ नमः शिवाय॥',
    translatedText: 'He who surrenders to Mahakal has nothing to fear from time or mortality. Om Namah Shivaya!',
    soundSnippetType: 'om-chant',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#1c1006', '#3d2008'],
    viewsCount: '7.8M',
    likesCount: 790000,
  },
  {
    id: 'dev-hi-3',
    title: 'राधे राधे जपो चले आएंगे बिहारी · श्री वृन्दावन',
    movie: 'वृन्दावन धाम महिमा (Vrindavan Bliss)',
    language: 'hi',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Gaurav Krishna Goswami / Chitra Vichitra',
    dialogueOrLyrics: 'राधे राधे जपो चले आएंगे बिहारी, आएगी बिहारी चले आएंगे बिहारी... राधे मेरी स्वामिनी मैं राधे को दास!',
    translatedText: 'Sing Radhe Radhe with pure love, and Shri Krishna will arrive to illuminate your soul.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 22,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#3b1b05', '#612a06'],
    viewsCount: '6.2M',
    likesCount: 650000,
  },

  // (B) PUNJABI DEVOTIONAL (GURBANI)
  {
    id: 'dev-pa-1',
    title: 'ੴ ਇਕ ਓਅੰਕਾਰ ਸਤਿਨਾਮੁ · ਜਪੁਜੀ ਸਾਹਿਬ ਮੂਲ ਮੰਤਰ',
    movie: 'ਸ਼੍ਰੀ ਹਰਿਮੰਦਰ ਸਾਹਿਬ ਅੰਮ੍ਰਿਤਸਰ (Golden Temple Gurbani)',
    language: 'pa',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Bhai Harjinder Singh Ji Sri Nagar Wale',
    dialogueOrLyrics: 'ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ॥ ਜਪੁ॥ ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ॥',
    translatedText: 'One Universal Creator God, Truth is His Name, Fearless, without enmity, Immortal, Self-existent.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 22,
    isPremium: false, // FREE
    gradientColors: ['#381c03', '#5c3108'],
    viewsCount: '5.1M',
    likesCount: 540000,
  },
  {
    id: 'dev-pa-2',
    title: 'ਵਾਹਿਗੁਰੂ ਸਿਮਰਨ · ਮਨ ਨੂੰ ਸ਼ਾਂਤੀ ਤੇ ਸੁੱਖ',
    movie: 'ਵਾਹਿਗੁਰੂ ਨਾਮ ਸਿਮਰਨ (Waheguru Simran)',
    language: 'pa',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'ਗੁਰਬਾਣੀ ਵਿਚਾਰ (Gurbani Katha)',
    dialogueOrLyrics: 'ਜਦੋਂ ਤੂੰ ਪ੍ਰਭੂ ਦੇ ਚਰਨਾਂ ਵਿੱਚ ਅਰਦਾਸ ਕਰਦਾ ਹੈਂ, ਤਾਂ ਤੇਰੇ ਸਾਰੇ ਦੁੱਖ-ਕਲੇਸ਼ ਦੂਰ ਹੋ ਜਾਂਦੇ ਨੇ। ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਿਹ!',
    translatedText: 'When you bow before the Almighty, all worldly sorrows dissolve into peace.',
    soundSnippetType: 'om-chant',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#291402', '#4d2807'],
    viewsCount: '3.8M',
    likesCount: 390000,
  },

  // (C) TAMIL DEVOTIONAL (முருகா & சிவம்)
  {
    id: 'dev-ta-1',
    title: 'வெற்றிவேல் முருகனுக்கு அரோகரா · கந்த சஷ்டி கவசம்',
    movie: 'திருச்செந்தூர் முருகன் பக்தி (Murugan Bhakti)',
    language: 'ta',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Soolamangalam Sisters / Mahanadhi Shobana',
    dialogueOrLyrics: 'துதிப்போர்க்கு வல்வினைபோம் துன்பம்போம் நெஞ்சில் பதிப்போர்க்கு செல்வம் பலித்துக் கதித்தோங்கும்! ஓம் சரவணபவ॥',
    translatedText: 'For those who chant Murugan’s name with devotion, all troubles flee and divine grace overflows!',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#3b1704', '#662a08'],
    viewsCount: '4.7M',
    likesCount: 460000,
  },
  {
    id: 'dev-ta-2',
    title: 'சிவாய நம ஓம் · அன்பே சிவம் திருவாசகம்',
    movie: 'திருவாசகம் & சிவன் பக்தி (Shiva Aradhana)',
    language: 'ta',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'மாணிக்கவாசகர் அருளியது',
    dialogueOrLyrics: 'தென்னாடுடைய சிவனே போற்றி! என்னாட்டவர்க்கும் இறைவா போற்றி! அன்பும் சிவமும் இரண்டென்பர் அறிவிலார், அன்பே சிவமாவது ஆரும் அறிகிலார்.',
    translatedText: 'Salutations to Shiva who dwells everywhere! Love and Shiva are one and the same truth.',
    soundSnippetType: 'om-chant',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#2e0c05', '#57180b'],
    viewsCount: '3.2M',
    likesCount: 310000,
  },

  // (D) TELUGU DEVOTIONAL (వెంకటేశ్వర & శివ)
  {
    id: 'dev-te-1',
    title: 'గోవిందా గోవిందా · తిరుపతి వేంకటేశ్వర సుప్రభాతం',
    movie: 'తిరుమల తిరుపతి దేవస్థానం (Tirupati Balaji)',
    language: 'te',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'M. S. Subbulakshmi (సుబ్బలక్ష్మి)',
    dialogueOrLyrics: 'కౌసल्या సుప్రజా రామ పూర్వా సంధ్యా ప్రవర్తతే! ఏడు కొండలవాడా వెంకటరమణా గోవిందా గోవిందా!',
    translatedText: 'Lord of the Seven Hills, Venkateswara, may Your holy presence bestow peace on all living beings.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#3b1804', '#6b2d07'],
    viewsCount: '5.6M',
    likesCount: 580000,
  },
  {
    id: 'dev-te-2',
    title: 'శివ తాండవ స్తోత్రం · హర హర మహాదేవ శంభో',
    movie: 'శివ భక్తి గీతాలు (Shiva Stotram)',
    language: 'te',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'ఎస్. పి. బాలసుబ్రహ్మణ్యం (SPB)',
    dialogueOrLyrics: 'జటాటవీగలజ్జలప్రవాహపావితస్థలే గలేవలంబ్య లంబితాం భుజంగతుంగమాలికామ్! హర హర మహాదేవ శంభో శంకరా!',
    translatedText: 'From the forest of Shiva’s matted locks flows the sacred Ganga! Victory to the supreme Mahadeva.',
    soundSnippetType: 'om-chant',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#290f04', '#4f1e09'],
    viewsCount: '4.1M',
    likesCount: 420000,
  },

  // (E) ODIA DEVOTIONAL (ଜୟ ଜଗନ୍ନାଥ)
  {
    id: 'dev-or-1',
    title: 'ଜୟ ଜଗନ୍ନାଥ ସ୍ୱାମୀ ନୟନ ପଥଗାମୀ ଭବତୁ ମେ',
    movie: 'ଶ୍ରୀ ଜଗନ୍ନାଥ ମହାପ୍ରଭୁ ଭଜନ (Puri Dham)',
    language: 'or',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Bhikari Bal (ଭିକାରୀ ବଳ)',
    dialogueOrLyrics: 'କାଳିଆ ସାଆନ୍ତ ହେ, ତୁମେ ମୋର ଦୁଃଖ ହରଣ କର! ଜଗନ୍ନାଥ ସ୍ୱାମୀ ନୟନ ପଥଗାମୀ ଭବତୁ ମେ॥',
    translatedText: 'O Mahaprabhu Jagannath, bless our sight with Your divine compassion and take away our sorrow.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#381a04', '#632e08'],
    viewsCount: '3.4M',
    likesCount: 340000,
  },
  {
    id: 'dev-or-2',
    title: 'ବଡ଼ଦାଣ୍ଡର ଧୂଳି ମୋର ମଥାର ଚନ୍ଦନ',
    movie: 'ରଥଯାତ୍ରା ପୁରୀ ଭଜନ (Rath Yatra)',
    language: 'or',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'ଜଗନ୍ନାଥ ଭକ୍ତ (Puri Sevayat)',
    dialogueOrLyrics: 'ଯେବେ ରଥ ଉପରେ ଚକାଡୋଳା ବସିବେ, ସେତେବେଳେ ସାରା ଜଗତ ତାଙ୍କ ପ୍ରେମରେ ନାଚି ଉଠିବ! ଜୟ ଜଗନ୍ନାଥ!',
    translatedText: 'When the Lord of the universe mounts the chariot, all realms sing in boundless devotion!',
    soundSnippetType: 'temple-bells',
    durationSeconds: 18,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#291203', '#4a2307'],
    viewsCount: '2.5M',
    likesCount: 260000,
  },

  // (F) BANGLA DEVOTIONAL (জয় মা তারা & কীর্তন)
  {
    id: 'dev-bn-1',
    title: 'জয় মা তারা · তুমি আমার মা আর আমি তোমার সন্তান',
    movie: 'তারা মায়ের গান ও শ্যামাসঙ্গীত (Tara Maa Bhakti)',
    language: 'bn',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Pannalal Bhattacharya / Ramprasad Sen',
    dialogueOrLyrics: 'মাগো আনন্দময়ী নিরানন্দ কোরো না! আমায় রাখো মা তোমার চরণতলে, জগতের সব জ্বালা ভুলিয়ে দাও।',
    translatedText: 'O Blissful Mother, hold me at your holy feet and let all earthly pains dissolve.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#381109', '#662214'],
    viewsCount: '3.6M',
    likesCount: 370000,
  },
  {
    id: 'dev-bn-2',
    title: 'হরে কৃষ্ণ হরে রাম · চৈতন্য মহাপ্রভুর পরম সংকীর্তন',
    movie: 'নবদ্বীপ শ্রীচৈতন্য লীলা (Gauranga Kirtan)',
    language: 'bn',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Kishore Das / Radharani Kirtan',
    dialogueOrLyrics: 'হরে কৃষ্ণ হরে কৃষ্ণ কৃষ্ণ কৃষ্ণ হরে হরে, হরে রাম হরে রাম রাম রাম হরে হরে! বলো হরিবোল হরিবোল!',
    translatedText: 'Chant the names of Krishna and Rama to awaken inner bliss and unconditional love.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 22,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#3b1805', '#612a09'],
    viewsCount: '2.8M',
    likesCount: 290000,
  },

  // (G) BHOJPURI DEVOTIONAL (छठी मैया & बोल बम)
  {
    id: 'dev-bho-1',
    title: 'काँच ही बाँस के बहँगीया · पावन छठ गीत',
    movie: 'छठी मैया के पावन व्रत (Chhath Mahaparv)',
    language: 'bho',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Sharda Sinha (स्वर कोकिला शारदा सिन्हा)',
    dialogueOrLyrics: 'काँच ही बाँस के बहँगीया, बहँगी लचकत जाए... बाटे हो ना बलम जी करहिया, बहँगी घाटे पहुंचाए! जय छठी मईया!',
    translatedText: 'The sacred bamboo offerings sway gracefully on the way to the river; blessings of Chhathi Maiya on all.',
    soundSnippetType: 'festive-shehnai',
    durationSeconds: 22,
    isPremium: false, // FREE
    gradientColors: ['#3b1905', '#6b2e0b'],
    viewsCount: '8.2M',
    likesCount: 880000,
  },
  {
    id: 'dev-bho-2',
    title: 'हर हर महादेव बोल बम · बाबा बैद्यनाथ धाम',
    movie: 'देवघर काँवरिया भजन (Bol Bam)',
    language: 'bho',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'Manoj Tiwari / Pawan Singh',
    dialogueOrLyrics: 'गेरुआ रंग में रंग गईल संसार! जब तक सांस रही तब तक बाबा बैद्यनाथ के जयकारा गूंजी! बोल बम का नारा है, बाबा एक सहारा है!',
    translatedText: 'The whole world turns saffron with devotion to Lord Shiva at Baidyanath Dham!',
    soundSnippetType: 'temple-bells',
    durationSeconds: 16,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#2e1305', '#52230a'],
    viewsCount: '4.9M',
    likesCount: 470000,
  },

  // (H) MARATHI DEVOTIONAL (विठू माऊली & गणपती)
  {
    id: 'dev-mr-1',
    title: 'विठू माऊली तू माउली जगाची · पंढरपूर वारी',
    movie: 'संत ज्ञानेश्वर व तुकाराम अभंग (Pandharpur Wari)',
    language: 'mr',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Sudhir Phadke / Ajit Kadkade',
    dialogueOrLyrics: 'विठू माऊली तू, माऊली जगाची... मायेची सावली आम्हा लेकरांची! जय जय रामकृष्ण हरी, जय जय विठ्ठल रुखमाई!',
    translatedText: 'O Vitthal, divine mother of the universe, your gentle shelter shields every devotee.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#3b1904', '#662d08'],
    viewsCount: '4.5M',
    likesCount: 450000,
  },
  {
    id: 'dev-mr-2',
    title: 'गणपती बाप्पा मोरया, पुढच्या वर्षी लवकर या!',
    movie: 'लालबागचा राजा उत्सव (Lalbaugcha Raja)',
    language: 'mr',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'गणेश भक्त मंडळ',
    dialogueOrLyrics: 'सुखकर्ता दुःखहर्ता वार्ता विघ्नाची, नुरवी पुरवी प्रेम कृपा जयाची! गणपती बाप्पा मोरया, मंगलमूर्ती मोरया!',
    translatedText: 'Remover of all hurdles and giver of boundless joy, Lord Ganesha blesses us all!',
    soundSnippetType: 'festive-shehnai',
    durationSeconds: 16,
    isPremium: true, // ₹49 VIP SPECIAL
    gradientColors: ['#2e1005', '#571e0a'],
    viewsCount: '5.8M',
    likesCount: 620000,
  },

  // (I) GUJARATI DEVOTIONAL (દ્વારકાધીશ & કૃષ્ણ)
  {
    id: 'dev-gu-1',
    title: 'મારો દ્વારકાધીશ જે કરે એ ઉત્તમ જ કરે',
    movie: 'દ્વારકાધીશ ભક્તિ ગીત (Dwarka Dham)',
    language: 'gu',
    type: 'dialogue',
    genre: 'devotional',
    actorOrSinger: 'કૃષ્ણ ભક્ત (Dwarka Sevak)',
    dialogueOrLyrics: 'જેના માથે મારો દ્વારકાધીશ હાથ મૂકે એને દુનિયામાં કોઈ હરાવી ના શકે! જય શ્રી કૃષ્ણ, રાધે રાધે!',
    translatedText: 'The one who rests under Dwarkadhish’s grace can never be defeated by worldly challenges.',
    soundSnippetType: 'romantic-flute',
    durationSeconds: 16,
    isPremium: false, // FREE
    gradientColors: ['#381804', '#632b07'],
    viewsCount: '3.1M',
    likesCount: 320000,
  },

  // (J) KANNADA DEVOTIONAL (ಧರ್ಮಸ್ಥಳ ಮಂಜುನಾಥ)
  {
    id: 'dev-kn-1',
    title: 'ಓಂ ನಮಃ ಶಿವಾಯ · ಧರ್ಮಸ್ಥಳ ಮಂಜುನಾಥ ಸ್ವಾಮಿ',
    movie: 'ಶ್ರೀ ಮಂಜುನಾಥ ಭಕ್ತಿ ಸುಧೆ (Manjunatha Bhakti)',
    language: 'kn',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'K. J. Yesudas (ಯೇಸುದಾಸ್)',
    dialogueOrLyrics: 'ಓಂ ಮಹಾಪ್ರಾಣ ದೀಪಂ ಶಿವಂ ಶಿವಂ! ಧರ್ಮಸ್ಥಳದ ಮಂಜುನಾಥ ಸ್ವಾಮಿ ಸದಾ ನಮ್ಮನ್ನು ರಕ್ಷಿಸಲಿ. ಹರ ಹರ ಮಹಾದೇವ!',
    translatedText: 'May Lord Manjunatha of Dharmasthala forever protect and guide our lives with holy light.',
    soundSnippetType: 'om-chant',
    durationSeconds: 20,
    isPremium: false, // FREE
    gradientColors: ['#2e1405', '#522409'],
    viewsCount: '2.9M',
    likesCount: 290000,
  },

  // (K) HARYANVI DEVOTIONAL (भोले की भक्ति)
  {
    id: 'dev-hr-1',
    title: 'भोलेनाथ का डमरू बाजे · हर हर शंभू',
    movie: 'देसी भोले भंडारी भजन (Bhole Ka Deewana)',
    language: 'hr',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Masoom Sharma / Ajay Hooda',
    dialogueOrLyrics: 'भोले का चेला सूं, कदे घमंड ना करूँ! जब तक सिर पे महाकाल का हाथ सै, मौत भी दूर भागे सै लाडलो।',
    translatedText: 'Devoted to Bholenath with humble heart; under Mahakal’s protection, fear dissolves.',
    soundSnippetType: 'temple-bells',
    durationSeconds: 18,
    isPremium: false, // FREE
    gradientColors: ['#331505', '#592408'],
    viewsCount: '4.2M',
    likesCount: 440000,
  },

  // (L) ENGLISH DEVOTIONAL (COSMIC CHANTS)
  {
    id: 'dev-en-1',
    title: 'Gayatri Mantra & Maha Mrityunjaya · Cosmic Light',
    movie: 'Vedic Chants of India (Universal Peace)',
    language: 'en',
    type: 'song',
    genre: 'devotional',
    actorOrSinger: 'Anuradha Paudwal / Sacred Chants Ensemble',
    dialogueOrLyrics: 'Om Bhur Bhuva Swaha, Tat Savitur Varenyam, Bhargo Devasya Dheemahi, Dhiyo Yo Nah Prachodayat. May divine light illuminate our intellect.',
    translatedText: 'We meditate on the supreme transcendental radiance that inspires our understanding.',
    soundSnippetType: 'om-chant',
    durationSeconds: 22,
    isPremium: false, // FREE
    gradientColors: ['#361603', '#5c2707'],
    viewsCount: '6.5M',
    likesCount: 710000,
  },
];
